version: '3.9'

services:

  database_mongodb_01:
    image: mongo:6.0.12
    container_name: database-mongodb-01
    platform: linux/arm64/v8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=superadmin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - VIRTUAL_PORT=27017
      - TERM=xterm
      - AUTH=yes
    volumes:
      - ./backup:/backup
      - ./data/mongodb_01:/data/db
    ports:
      - "27017:27017"
    networks:
      - database_mongodb_network
    command: mongod --auth

networks:
  database_mongodb_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24
          gateway: 172.11.0.1
